config:
  prometheus:
    enabled: false
    ingressWhitelist:
      enabled: false
frontend:
  image:
    tag: "v1.37.2"
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 1Gi
  ingress:
    enabled: true
    className: "kong"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/https-redirect-status-code: "301"
      konghq.com/protocols: "https"
      konghq.com/strip-path: "false"
    hostname: "blockscout.ascendbit.network"
    tls:
      enabled: true
      secretName: blockscout-cert-tls
  env:
    NEXT_PUBLIC_AD_BANNER_PROVIDER: "none"
    NEXT_PUBLIC_AD_TEXT_PROVIDER: "none"
    NEXT_PUBLIC_API_HOST: "api-blockscout.ascendbit.network"
    NEXT_PUBLIC_API_PORT: "443"
    NEXT_PUBLIC_APP_HOST: "blockscout.ascendbit.network"
    NEXT_PUBLIC_APP_PORT: "443"
    NEXT_PUBLIC_IS_TESTNET: "false"
    NEXT_PUBLIC_NETWORK_ID: 9988
    NEXT_PUBLIC_NETWORK_NAME: "ABC BAAS"
    NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE: "validation"
blockscout:
  image:
    tag: "6.10.0"
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 3Gi
  ingress:
    enabled: true
    className: "kong"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/https-redirect-status-code: "301"
      konghq.com/plugins: response-header
      konghq.com/protocols: "https"
      konghq.com/strip-path: "false"
    hostname: "api-blockscout.ascendbit.network"
    tls:
      enabled: true
      secretName: api-blockscout-cert-tls
  env:
    ETHEREUM_JSONRPC_VARIANT: "besu"
    ETHEREUM_JSONRPC_HTTP_INSECURE: "true"
    ETHEREUM_JSONRPC_HTTP_URL: "http://besu-node-archive-1.besu.svc.cluster.local:8545"
    DATABASE_URL: "postgresql://blockscout:nyruNA3LZ4DIHhiw@10.202.72.11:5432/blockscout"
    ETHEREUM_JSONRPC_TRACE_URL: "http://besu-node-archive-1.besu.svc.cluster.local:8545"
    CHAIN_ID: "9988"
    NETWORK: "POA"
    SUBNETWORK: "POA Sokol"
    ETHEREUM_JSONRPC_WS_URL: "ws://besu-node-archive-1.besu.svc.cluster.local:8546"
    BLOCKSCOUT_HOST: "blockscout.ascendbit.network"
    BLOCKSCOUT_PROTOCOL: "http"
    SECRET_KEY_BASE: "uFwkcFHfs9aLjHljGHKo726xieAuMHsH4d5jtqWnEBMgFSGCNA/L0BFoh85YASQt"
    DISABLE_EXCHANGE_RATES: "true"
    POOL_SIZE_API: 20
    POOL_SIZE: 20
    ECTO_USE_SSL: "false"
    BLOCK_RANGES: "5715219..latest"
    FIRST_BLOCK: 5715219
    TRACE_FIRST_BLOCK: 5715219
    API_GRAPHQL_ENABLED: "false"
    INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: 1
    INDEXER_CATCHUP_BLOCKS_CONCURRENCY: 1
    INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "true"
    TOKEN_ID_MIGRATION_FIRST_BLOCK: 5715219
    SHOW_PRICE_CHART: "false"
    SHOW_TXS_CHART: "false"
    TXS_STATS_ENABLED: "false"
stats:
  enabled: false
  image:
    tag: "v2.0.0"
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 500m
      memory: 1Gi
  ingress:
    enabled: true
    className: "kong"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/https-redirect-status-code: "301"
      konghq.com/plugins: response-header
      konghq.com/protocols: "https"
      konghq.com/strip-path: "false"
    hostname: "stats-blockscout.ascendbit.network"
    tls:
      enabled: true
      secretName: stats-blockscout-cert-tls
  env:
    STATS__BLOCKSCOUT_DB_URL: "postgresql://blockscout:nyruNA3LZ4DIHhiw@blockscout-rds.in.ascendbit.network:5432/blockscout"
    STATS__DB_URL: "postgresql://blockscout-stats:iyi2psVgJ4JLrtkf@blockscout-rds.in.ascendbit.network:5432/blockscout-stats"
    STATS__RUN_MIGRATIONS: "true"